---
title: "Data cleaning and exploration in R"
author: "Nsubuga Emmnauel Reagan"
date: "2024-04-24"
output: pdf_document
---

```{r}
install.packages(c("nycflights13", "gapminder", "Lahman"))
```

Data visua;isation with the Tidyverse

```{r}
library(tidyverse)
```

```{r}
ggplot(data = mpg) + geom_point(mapping = aes(x = displ, y = hwy, color = class))
```
```{r}
ggplot(data = mpg) +
 geom_point(mapping = aes(x = displ, y = hwy, size = class))
 
```
```{r}
 ggplot(data = mpg) +
 geom_point(mapping = aes(x = displ, y = hwy, alpha = class))
```
```{r}
ggplot(data = mpg) +
 geom_point(mapping = aes(x = displ, y = hwy), color = "blue")
```
Facets

```{r}
ggplot(data = mpg) +
 geom_point(mapping = aes(x = displ, y = hwy)) +
 facet_wrap(~ class, nrow = 2)
```
```{r}
ggplot(data = mpg) +
 geom_point(mapping = aes(x = displ, y = hwy)) +
 facet_grid(drv ~ cyl)
```
```{r}
 ggplot(data = mpg) +
 geom_smooth(mapping = aes(x = displ, y = hwy, linetype = drv))
```
```{r}
 ggplot(data = mpg, mapping = aes(x = displ, y = hwy)) +
 geom_point(mapping = aes(color = class)) +
 geom_smooth()
```
```{r}
 ggplot(data = mpg, mapping = aes(x = displ, y = hwy)) +
 geom_point(mapping = aes(color = class)) +
 geom_smooth(
 data = filter(mpg, class == "subcompact"),
 se = FALSE
 )
```
```{r}
 ggplot(data = diamonds) +
 geom_bar(mapping = aes(x = cut))
```
```{r}
ggplot(data = diamonds) +
 stat_count(mapping = aes(x = cut))
```

```{r}
 ggplot(data = diamonds) +
 geom_bar(
 mapping = aes(x = cut, y = ..prop.., group = 1)
 )
```
```{r}
 ggplot(data = diamonds) +
 stat_summary(
 mapping = aes(x = cut, y = depth),
 fun.ymin = min,
 fun.ymax = max,
 fun.y = median
 )
```
```{r}
 ggplot(data = diamonds) +
 geom_bar(mapping = aes(x = cut, fill = cut))
```
```{r}
ggplot(data = diamonds) +
 geom_bar(mapping = aes(x = cut, color = cut))
```
```{r}
ggplot(data = diamonds) +
 geom_bar(mapping = aes(x = cut, fill = clarity))
```
```{r}
 ggplot(
 data = diamonds,
 mapping = aes(x = cut, fill = clarity)
 ) +
 geom_bar(alpha = 1/5, position = "identity")
 ggplot(
 data = diamonds,
 mapping = aes(x = cut, color = clarity)
 ) +
 geom_bar(fill = NA, position = "identity")
```
```{r}
 ggplot(data = diamonds) +
 geom_bar(
 mapping = aes(x = cut, fill = clarity),
 position = "fill"
 )
```
```{r}
 ggplot(data = diamonds) +
 geom_bar(
 mapping = aes(x = cut, fill = clarity),
 position = "dodge"
 )
```

```{r}
ggplot(data = mpg) +
 geom_point(
 mapping = aes(x = displ, y = hwy),
 position = "jitter"
 )
```

```{r}
 ggplot(data = mpg, mapping = aes(x = class, y = hwy)) +
 geom_boxplot()
```

```{r}
ggplot(data = mpg, mapping = aes(x = class, y = hwy)) +
 geom_boxplot() +
 coord_flip()
```

```{r}
 nz <- map_data("nz")
 ggplot(nz, aes(long, lat, group = group)) +
 geom_polygon(fill = "white", color = "black")
```

```{r}
 ggplot(nz, aes(long, lat, group = group)) +
 geom_polygon(fill = "white", color = "black") +
 coord_quickmap()
```

```{r}
 bar <- ggplot(data = diamonds) +
 geom_bar(
 mapping = aes(x = cut, fill = cut),
 show.legend = FALSE,
 width = 1
 ) +
 theme(aspect.ratio = 1) +
 labs(x = NULL, y = NULL)
 bar + coord_flip()
```

```{r}
bar + coord_polar()
```



